### ISSUE TITLE
Avoid writing to standard output

### ISSUE THREAD

**Issue by glopesdev** [bonsai-rx/harp#22]
`Device` nodes currently make a query for information on device ID, version, etc whenever the `PortName` property is assigned. This was once necessary when there was no other way to access information on the selected device.

In the long run, however, this is at best confusing, and at worst silently harmful. Because there is no way to filter information in the standard output terminal window, it can quickly become hard to know which device node is actually being displayed if there are multiple such nodes in the workflow. Furthermore, if the property is being assigned dynamically, this can lead to initialization errors at runtime and other potential resource access clashes.

In the latest version of the package, the `Device` class now has a dedicated property page where all information about the device can be explicitly checked. It is also now very easy to construct explicit device sources that test whether the hardware actually implements a specific `WhoAmI` value so there should be no need to manually check whether the device that is plugged in at a specific port is of the type we expect.

With these two features, I believe we are very close to the time when we can finally retire the standard output print outs. It would be great to collect in this thread what other reasons remain for keeping them.

**Comment by aspaNeuro** [comment]
It could be interesting to have integrated into the hardware a writable property where we can give names to each device to have meaningful names for devices according to the setup itself.
ex. PokesBoard
