### ISSUE TITLE
`ReadAsync` methods from `AsyncDevice` should return a HarpMessage 

### ISSUE THREAD

**Issue by bruno-f-cruz** [bonsai-rx/harp#37]
Example:
https://github.com/bonsai-rx/harp/blob/fd38d2f2eba52a190b300abf63758a104daecbb9/Bonsai.Harp/AsyncDevice.cs#L82

It would be helpful to return the full HarpMessage so we can recover the complete HarpMessage data, including the timestamp of the message.

**Comment by glopesdev** [comment]
This can be done by calling `CommandAsync` with a formatted Read message (e.g. using `HarpCommand.ReadByte`).
