### ISSUE TITLE
Alternatives to the deprecated SynchronizeTimestamp command

### ISSUE THREAD

**Issue by glopesdev** [bonsai-rx/harp#56]
A common requirement for experiments using Harp devices is to synchronize the device clock with the current UTC time at the beginning of an experiment or dataset.

This is done by sending a message to the `TimestampSeconds` register containing the number of seconds, which are computed from the host UTC clock to seconds using a specified reference time (e.g. midnight of 1904-1-1). This was previously done via a variant of the `DeviceCommand` operator, but there is no equivalent of this command for the current auto-generated interface which simply sets the register value directly.

Since this is such a common requirement it would make sense to create a dedicated operator for this. The outstanding question is whether we should also take the opportunity to rethink reference times in Harp, for example to allow calculating this time for other registers rather than just the `TimestampSeconds` register.

There are a few options to consider here:
1. Expose the `SynchronizeTimestamp` operator as a dedicated operator to construct the synchronization message exactly as before.
2. Add a new operator `CreateUtcTimestamp` that simply returns a timestamp in seconds from the current computer clock (using either a fixed- or user-specified time reference). This value can then be used to create the synchronization message timestamp.
3. Add a new operator `UtcTimestamp` that creates either a `Timestamped<T>` value with the current UTC to Harp clock for any input, or updates the UTC timestamp on an existing Harp message to reflect the converted UTC clock time. This could be used to quickly generate messages or values with UTC timestamps converted to Harp format (which could then be directly sent to the device, either for the `TimestampSeconds` register or other register commands.
4. Add an operator to offset the timestamp from an existing timestamped value or Harp message using a relative `TimeSpan`. This could be used to easily create timestamped messages relative to existing messages. The current UTC clock could be obtained by computing the offset between the current and desired clock under the reference time.

Happy to hear about other ideas in the comments.

**Comment by bruno-f-cruz** [comment]
After reading the notes, here are some thoughts:

I think we should create 2 operators tbh. One that handles the UTC setting (since, as you pointed out it is such a core feature of the protocol) 

Something like:
```
Properties:
DateTime Reference (optional, defaults to harp reference)

Overloads:
No input -> Takes the OS clock and outputs the `double seconds` that corresponds to OS - Reference
or 
Timestamped<T> -> outputs the `double seconds` that corresponds to Timestamp - Reference
```
Alternatively, instead of creating a new operator, these could be overloads for the "CreateMessage" and "Format" of the relevant address inside the Bonsai.Harp interface. (and only for that address)

----

And a second operator (I think similar to your 4.) that provides users with a simple way to manipulate harp timestamps. I think this should include something that takes a HarpMessage (coming from a device), and offsets it by `TimeSpan` or `Double` (seconds). Additionally, it should have an overload that allows users to "inject" a timestamp in the message (Think the output of CreateMessage). In this case, I think the most useful would be to have an overload that takes `Tuple<HarpMessage, Timestamp(`Double` or `DateTime`)> and also offsets it by the `Offset` property. 

```
Properties:
DateTime Offset (optional, defaults to 0)

Overloads:
HarpMessage -> Takes the harpmessage timestamp and offsets it by Offset
Tuple<HarpMessage, Timestamp(e.g. Double / DateTime)> -> Injects/replaces the timestamp of the incoming harp message by Timestamp + Offset
```

**Comment by glopesdev** [comment]
Reviewing the existing API it might be possible to do this by taking the existing `CreateMessage` and `CreateTimestamped` operators and introducing some missing overloads and properties.

### CreateMessage

The `CreateMessage` operator does not currently have an overload accepting `Timestamped<T>` objects ([see example](https://github.com/bonsai-rx/harp/blob/83cc7731ade2033b28a13cbb36e561454a304712/Bonsai.Harp/Device.Generated.cs#L2235)). If we simply add these missing overloads, we could have an explicit way to pass a timestamp to be used for message creation. For example:

```c#
public IObservable<HarpMessage> Process<TSource>(IObservable<Timestamped<TSource>> source)
{
    return source.Select(_ => ClockConfiguration.FromPayload(_.Seconds, MessageType, Value));
}
```

This would make `CreateMessage` equivalent to `Format` which already has overloads for passing a timestamped value in order to create timestamped messages.

At first I thought we should also provide an overload which would accept `HarpMessage` objects and use their timestamps directly. However, there is actually a big problem with this approach in that we would not be able distinguish between the case where you want to use the input timestamp, and the case where you simply use a raw `HarpMessage` as a trigger to create another message but you don't want to timestamp it.

A solution to make the distinction explicit is to have a trivial way to create a `Timestamped<HarpMessage>` object directly from a `HarpMessage`, which takes us to the `CreateTimestamped` overloads.

### CreateTimestamped

[`CreateTimestamped`](https://github.com/bonsai-rx/harp/blob/main/Bonsai.Harp/CreateTimestamped.cs) is the natural operator where we can add the optional `Offset` property. This operator already accepts overloads for both tuples with timestamp and tuples with `HarpMessage`. It wouldn't break anything of existing functionality to simply add the optional `Offset` to every created timestamp.

Furthermore, as discussed above, we could add a new overload that creates a `Timestamped<HarpMessage>` from a `HarpMessage`. This might seem like a redundant operation, since a `HarpMessage` already has a timestamp, but in fact this is not the case, for two reasons:
1. In fact, not all messages need to be timestamped (e.g. commands). If a non-timestamped message is passed to the input, the operator will throw an error;
2. The `Timestamped<HarpMessage>` type can be used to explicitly indicate that we want to use the timestamp to inject time into a created message, as discussed above.

The implementation is trivial and efficient, especially since `Timestamped<T>` is a struct so there will be no new allocations in the pipeline:

```c#
public IObservable<Timestamped<HarpMessage>> Process(IObservable<HarpMessage> source)
{
    return source.Select(message => Timestamped.Create(message, message.GetTimestamp()));
}
```

Finally, we could add one final overload to `CreateTimestamped` which simply converts from the reactive `Timestamped<T>` type to the corresponding Harp timestamped value:

```c#
public IObservable<Timestamped<T>> Process<T>(IObservable<System.Reactive.Timestamped<T>> source)
{
    return source.Select(_ =>
    {
        var seconds = _.Timestamp.UtcDateTime.Subtract(new DateTime(1904, 1, 1)).TotalSeconds;
        return Timestamped.Create(_.Value, seconds);
    });
}
```

With these in place, we could create and manipulate timestamps:

- Create a message timestamped from another message (with optional offset in `CreateTimestamped`):

<img src="https://github.com/bonsai-rx/harp/assets/5315880/22b622b8-f148-4683-a6f3-8ce07110bee3" height="75px" />

- Synchronize a Harp device with the local UTC clock on key press:

<img src="https://github.com/bonsai-rx/harp/assets/5315880/895f1c72-9797-4a55-9fee-99cbdc19eda4" height="75px" />

**Comment by bruno-f-cruz** [comment]
I agree with everything except the new overload from `CreateMessage`. Currently `CreateMessage` ignores any input information and solely uses the incoming sequence as a trigger source. I think breaking this rule would "blur" the line between the `CreateMessage` and `Format` operators, which I would like to keep. Would it not be an option to, in line with the current implementation, to alternatively expose the timestamp as a property perhaps (e.g. a double or a TimeSpan?)? 

For instance, in this example:
![image](https://github.com/bonsai-rx/harp/assets/7049351/54788bbb-78cb-4ea3-b876-a2254e3a7c85)
Wouldnt it suffice to use the `Format` operator instead of the `CreateMessage`? (I might be missing something). If I understand correctly, the last example will take care of all use cases, no?

Finally, coming back to my initial point, although I agree that it could be quickly done by your last example, I still think that a dedicated operator (or even just an include workflow tbh...) to wrap `Timestamp -> CreateTimestamped -> Seconds -> Device.TimestampSeconds` would be nice for the users.

**Comment by glopesdev** [comment]
> Would it not suffice to use the Format operator instead of the CreateMessage? (I might be missing something). If I understand correctly, the last example will take care of all use cases, no?

No, because we are creating a completely unrelated message payload. `Format` expects you to provide an already fully constructed value, but cannot act as a constructor with properties for complex types. For example I think this will be extremely useful for implementing virtual devices.

You could in theory use an extra timestamp property, but it would in my opinion confuse things, since as a user you see it in the properties as something to be edited "manually" and I cannot see a situation where you would ever want to set a fixed timestamp by hand (even when replaying you are getting timestamps from files).

I don't think the lines are blurred at all, in fact I think it's more consistent with the two overloads. The main difference between `Format` and `CreateMessage` is not the timestamp but the fact that one is a constructor and the other is not.

About the include workflow or operator for synchronising I agree it makes sense to expose a direct one, probably in this case I will just expose the `SynchronizeTimestamp` operator, but I also like the fact that you can build it from low-level building blocks.

**Comment by glopesdev** [comment]
> Currently, CreateMessage ignores any input information and solely uses the incoming sequence as a trigger source. I think breaking this rule would "blur" the line between the CreateMessage and Format operators, which I would like to keep.

Is the worry that you could pass a `Timestamped<T>` unintentionally and create a timestamped message by accident?

Another option to resolve this could be to have a property in the base class that simply indicates whether you use timestamps or not, or just generate `CreateTimestampedMessage` operators for the polymorphic the same way we do for `Parse` and `Format`. That way you could be really explicit about what you want and the compatible overloads would change accordingly.

**Comment by bruno-f-cruz** [comment]
> No, because we are creating a completely unrelated message payload. `Format` expects you to provide an already fully constructed value, but cannot act as a constructor with properties for complex types. For example I think this will be extremely useful for implementing virtual devices.

I see... uhm in that case, I like your suggestion of adding the `TimestampedPayload` dyad to the `CreateMessage` node. That way, users would at least need to be a bit more "intentional" about it.

**Comment by glopesdev** [comment]
There is a third option, which is to introduce a new type of base operator called `CreatePayload` which represent pure payload constructors, i.e. they only create the raw payload type itself. It would then be possible to take that fully constructed value and pass it into `Format` with a timestamp to create timestamped messages.

The pros is that it becomes possible to use the created payload types directly in the workflow. The cons is that it would require two steps to create a message from properties (unless we keep the `CreateMessage` operators anyway).

**Comment by bruno-f-cruz** [comment]
I feel this third option would just add an unnecessary step for most use cases. I'd rather go with your previously suggested solution of using the TimestampedPayload tbh. Unless you have a future implementing in mind that would benefit greatly from having this raw payload constructor.
