### ISSUE TITLE
Have access to the common registers Device information on the Device class

### ISSUE THREAD

**Issue by MicBoucinha** [bonsai-rx/harp#8]
It would be interesting to have access to the common registers that we currently cannot access directly through the Device class and that are common to all Harp devices. such as Firmware and Hardware versions (major and minor, could be presented as a Version) as well as the who_am_i and serial_number.

**Comment by glopesdev** [comment]
I was divided on this one. On the one hand it seems obviously useful, but it's interesting that by using the `Device` classes in the assembly, we have so far been able to implement entire device APIs without depending on this information. This has the advantage of making code easier to migrate, if in the future there is an update to the protocol (e.g. if we change from 8-bit to 32-bit microcontrollers).

I'm still leaning towards including it though.

**Comment by glopesdev** [comment]
I remember that the plan though was to leave it out this time and see how much is it really necessary. I might go with that for now, unless you have a specific use case in mind?

**Comment by MicBoucinha** [comment]
To be honest it would be simply to allow the GUI users to know (also easier for support) the firmware and hardware versions of the Harp device that is connected. This without sending the commands again, since that information is already gathered and printed to the Console on GetDeviceName. 

Not sure how the firmware updating is implemented, but it could also be useful for a validation of the firmware version installed vs the one to install.

Those are the two situations that I can see where it could be useful for now, but most likely I am missing a better way to get that information.

Thanks for considering the suggestion!

**Comment by glopesdev** [comment]
These are definitely good points. I will leave the issue open and aim to push it in the next release together with the common GUI elements.

**Comment by glopesdev** [comment]
This was fixed in f06e4b3e6c141f5b4be3812d25be6ed018003f46.
